.class public final Lo/TradingBotsCmOpenOrderFragmentspecialinlinedviewModelsdefault5;
.super Lo/StrategyFundsAssetParentFragment;
.source "SourceFile"


# annotations
.annotation system Ldalvik/annotation/Signature;
    value = {
        "<R::",
        "Lo/BaseStrategyFundsAssetFragmentspecialinlinedviewModelsdefault1;",
        ">",
        "Lo/StrategyFundsAssetParentFragment<",
        "TR;>;"
    }
.end annotation


# instance fields
.field private final a:Lcom/google/android/gms/common/api/Status;


# virtual methods
.method public final b(JLjava/util/concurrent/TimeUnit;)Lo/BaseStrategyFundsAssetFragmentspecialinlinedviewModelsdefault1;
    .locals 0
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(J",
            "Ljava/util/concurrent/TimeUnit;",
            ")TR;"
        }
    .end annotation

    .line 2
    new-instance p1, Ljava/lang/UnsupportedOperationException;

    const-string p2, "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()"

    invoke-direct {p1, p2}, Ljava/lang/UnsupportedOperationException;-><init>(Ljava/lang/String;)V

    throw p1
.end method

.method public final d(Lo/BaseStrategyFundsAssetFragmentspecialinlinedviewModelsdefault3;)V
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Lo/BaseStrategyFundsAssetFragmentspecialinlinedviewModelsdefault3<",
            "-TR;>;)V"
        }
    .end annotation

    .line 1
    new-instance p1, Ljava/lang/UnsupportedOperationException;

    const-string v0, "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()"

    invoke-direct {p1, v0}, Ljava/lang/UnsupportedOperationException;-><init>(Ljava/lang/String;)V

    throw p1
.end method

.method public final d(Lo/StrategyFundsAssetParentFragment$DropdropElements4;)V
    .locals 1

    .line 1
    new-instance p1, Ljava/lang/UnsupportedOperationException;

    const-string v0, "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()"

    invoke-direct {p1, v0}, Ljava/lang/UnsupportedOperationException;-><init>(Ljava/lang/String;)V

    throw p1
.end method

.method final e()Lcom/google/android/gms/common/api/Status;
    .locals 1

    .line 65354
    iget-object v0, p0, Lo/TradingBotsCmOpenOrderFragmentspecialinlinedviewModelsdefault5;->a:Lcom/google/android/gms/common/api/Status;

    return-object v0
.end method
