.class public interface abstract Lo/getMaximumSize;
.super Ljava/lang/Object;
.source "SourceFile"

# interfaces
.implements Lkotlin/jvm/functions/Function2;
.implements Lkotlin/jvm/functions/Function3;
.implements Lo/Web3DeeplinkInterceptor;
.implements Lo/Web3DeeplinkInterceptorprocess1;
.implements Lo/TWNetworkProxycall1;
.implements Lo/WalletConnectActivityonWalletConnect21;
.implements Lo/WalletConnectActivityloadSessionList11;
.implements Lo/WalletConnectActivityloadSessionList1;
.implements Lo/WalletNecessaryDataHelpergetBuwConfig21;
.implements Lo/WalletNecessaryDataHelpergetNetworkMappingList2;
.implements Lo/WalletNecessaryDataHelpergetSupportNetwork1;
.implements Lo/Web3ExtensionWalletToolsderiveKeyShare1;
.implements Lo/Web3ExtensionWalletToolshandleExtensionSign1;
.implements Lo/ActiveState;
.implements Lo/Scheduler;
.implements Lo/WhiteScreenDetectHelpercheckWhiteScreen11;
.implements Lo/EventpostInScope1;
.implements Lo/EventobserveInternal1;
.implements Lo/WalletBackupActivity;


# annotations
.annotation system Ldalvik/annotation/Signature;
    value = {
        "Ljava/lang/Object;",
        "Lkotlin/jvm/functions/Function2<",
        "Lo/defaultgetSupportedResolutions;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lkotlin/jvm/functions/Function3<",
        "Ljava/lang/Object;",
        "Lo/defaultgetSupportedResolutions;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lo/Web3DeeplinkInterceptor<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Lo/defaultgetSupportedResolutions;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lo/Web3DeeplinkInterceptorprocess1<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Lo/defaultgetSupportedResolutions;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lo/TWNetworkProxycall1<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Lo/defaultgetSupportedResolutions;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lo/WalletConnectActivityonWalletConnect21<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Lo/defaultgetSupportedResolutions;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lo/WalletConnectActivityloadSessionList11<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Lo/defaultgetSupportedResolutions;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lo/WalletConnectActivityloadSessionList1<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Lo/defaultgetSupportedResolutions;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lo/WalletNecessaryDataHelpergetBuwConfig21<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Lo/defaultgetSupportedResolutions;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lo/WalletNecessaryDataHelpergetNetworkMappingList2<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Lo/defaultgetSupportedResolutions;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lo/WalletNecessaryDataHelpergetSupportNetwork1<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Lo/defaultgetSupportedResolutions;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lo/Web3ExtensionWalletToolsderiveKeyShare1<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Lo/defaultgetSupportedResolutions;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lo/Web3ExtensionWalletToolshandleExtensionSign1<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Lo/defaultgetSupportedResolutions;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lo/ActiveState<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Lo/defaultgetSupportedResolutions;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lo/Scheduler<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Lo/defaultgetSupportedResolutions;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lo/WhiteScreenDetectHelpercheckWhiteScreen11<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Lo/defaultgetSupportedResolutions;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lo/EventpostInScope1<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Lo/defaultgetSupportedResolutions;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lo/EventobserveInternal1<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Lo/defaultgetSupportedResolutions;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lo/WalletBackupActivity<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Lo/defaultgetSupportedResolutions;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;"
    }
.end annotation
